spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

amazons3:
  endPoint: ${S3_URL}
  regionName: kr-standard
  accessKey: ${S3_ACCESSKEY}
  secretKey: ${S3_SECRETKEY}
  bucketName: ${S3_BUCKETNAME}
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testDB;DATABASE_TO_UPPER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
---