spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url:
    username:
    password:

amazons3:
  endPoint: https://kr.object.ncloudstorage.com
  regionName: kr-standard
  accessKey:
  secretKey:
  bucketName:
